[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Build command that includes server setup
[build.processing]
  skip_processing = false

# Server-side functionality
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect API calls to server
[[redirects]]
  from = "/api/stripe/*"
  to = "http://localhost:3001/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# SPA routing redirects
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/orders/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/order/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/menu/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/payment/*"
  to = "/index.html"
  status = 200

# Catch-all for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORS headers for API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Stripe-Signature"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
